### ISSUE TITLE
Frage zu Körpergewicht

### ISSUE THREAD

**Issue by Tim-Steinbach-UKB** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#1]
https://simplifier.net/medizininformatikinitiative-modul-intensivmedizin/miikoerpergewicht

wir haben hier bei vs-cat UND bei sct in den Slices dasselbe Binding drin. Beim SCT sollten snomed codes rein, das Binding zeigt aber auf Freitext ValueSet (https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/78929)

Das untere Binding muss weg oder? --> eh optional
und bestenfalls ein Fixedvalue rein --> FixedValue weil das beim "koerpergewicht" immer das selbe sein sollte?

Frage David (ggf copy paste fehler):
Ich weiß dann aber nicht so ganz was ich bei den (allgemeinen) Vitaldaten da reinsetze. (Profil: https://simplifier.net/medizininformatikinitiative-modul-intensivmedizin/sd_mii_icu_monitoring_und_vitaldaten-duplicate-3 )

**Comment by christmueller** [comment]
Ist bereits erledigt im Profil.
