### ISSUE TITLE
ValueSet "VS MII ICU Code Observation extrakorporale Verfahren [ISO11073]" has empty definition

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#12]
The ValueSet "VS MII ICU Code Observation extrakorporale Verfahren [ISO11073]" (canonical `https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/ValueSet/code-observation-extrakorporale-verfahren-iso11073`, [repo link](https://github.com/medizininformatik-initiative/kerndatensatzmodul-intensivmedizin/blob/master/ValueSet/VS_MII_ICU_Code_Observation_extrakorporale_Verfahren_ISO11073.json)) has no definition/`compose`. This is likely not intended.

**Comment by jpwiedekopf** [comment]
This is somewhat related to #11, as the CodeSystem is missing.

**Comment by Tim-Steinbach-UKB** [comment]
We will delete VS and remove Slice.
