### ISSUE TITLE
Blutgasanalyse

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#13]
Profile/Beispiele für BGA mit PaCO2, PaO2, FiO2, pH in das Modul aufnehmen?

**Comment by christmueller** [comment]
Felix hatte seinerzeit entschieden, dass - auch wenn BGAs an sich Artefakte der Behandlung auf ICU sind - aufgrund ihrer Struktur im Modul Labor aufgehoben sein sollen. 

Wir nehmen den Issue aber nochmal mit zur Diskussion und prüfen, ob wir im IG einen Abschnitt zu BGAs machen mit Beispielen und Verweis auf die Profile des KDS Moduls Labor, ohne aber explizit Profile anzugeben oder zu erben.
