### ISSUE TITLE
Validierungs-Error bei Körpergröße

### ISSUE THREAD

**Issue by chaverkamp** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#14]
Ich habe bei der Beispielressource diese beiden Fehler

Error
Line: 22, Col:8
Profile https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/koerpergroesse|1.0.0, Element matches more than one slice - loinc, loinc-fhir-core
Error
Line: 37, Col:4
This element does not match any known slice defined in the profile https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/koerpergroesse|1.0.0 and slicing is CLOSED: Observation.effective.ofType(Period): Does not match slice 'effectiveDateTime' (discriminator: ($this is dateTime))

**Comment by christmueller** [comment]
outdated. Ist erledigt.
