### ISSUE TITLE
SearchParameter.code

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#16]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-intensivmedizin/blob/4edcff52b9b627867ade5e3af75e61ad43e7b9da/SearchParameter/sp-mii-icu-device-property-type.json#L22

`.` in SearchParameter.code sollte vermieden und durch `-` ersetzt werden. Die Suchparameter funktionieren sonst nicht, weil `.` schon beim Chaining von Parametern verwendet wird.

**Comment by Gauxi** [comment]
Das betrifft auch die Component Search Parameter

**Comment by christmueller** [comment]
erledigt
