### ISSUE TITLE
Suchparameter Observation.referenceRange

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#17]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-intensivmedizin/blob/4edcff52b9b627867ade5e3af75e61ad43e7b9da/SearchParameter/sp-mii-icu-observation-referencerange.json#L27

Dieser Suchparameter und der für Observation.component.referenceRange funktionieren nicht. Da referenceRange ein BackboneElement ist, muss hier angegeben werden, nach welchem Element genau gesucht werden soll und dann ist ggf. der `type` nicht `token` sondern `quantity`.

**Comment by christmueller** [comment]
Danke für den Hinweis und die Unterstützung. Aktualisierte Suchparameter sind hochgeladen für referernceRange-low, referernceRange-high sowie als composite für referernceRange.

**Comment by christmueller** [comment]
Danke für den Hinweis und die Unterstützung. Aktualisierte Suchparameter sind hochgeladen für referernceRange-low, referernceRange-high sowie als composite für referernceRange.

**Comment by christmueller** [comment]
Test ausstehend.
