### ISSUE TITLE
Pattern auf flascher Ebene für sd-mii-icu-extrakorporales-verfahren

### ISSUE THREAD

**Issue by christmueller** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#2]
Das Pattern für die slices von Procedure.code ist nicht auf dem slice selbst definiert, sondern auf coding.system. Sollte hochgezogen werden (wie bei Procedure.category). 

https://github.com/medizininformatik-initiative/kerndatensatzmodul-intensivmedizin/blob/master/ressourcen-profile/sd-mii-icu-extrakorporales-verfahren.json

**Comment by Tim-Steinbach-UKB** [comment]
Done
