### ISSUE TITLE
Abhängigkeitskonflikt durch unlisted de.basisprofil.r4 1.5.0-ballot2

### ISSUE THREAD

**Issue by KutSaleh** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#22]
Im Package `de.medizininformatikinitiative.kerndatensatz.icu 2024.0.0-alpha2` ist eine Abhängigkeit auf das Package `de.basisprofil.r4 1.5.0-ballot2`, welche unlisted ist. Außerdem hat `de.medizininformatikinitiative.kerndatensatz.prozedur 2024.0.0-ballot` (welches ebenfall seine Abhängigkeit des -ICUPackages ist) eine Abhängigkeit auf `de.basisprofil.r4 1.4.0`. Damit schließen sich die Abhängigkeiten gegenseitig aus.

Die letzte nutzbare Version ist `de.medizininformatikinitiative.kerndatensatz.icu 2024.0.0-alpha1`.

**Comment by Tim-Steinbach-UKB** [comment]
Hi, wir haben jetzt ein neues Package erstellt:
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.icu/2024.0.0-alpha3
Das ist der Stand von März mit geändertem VS und dependency. Wir haben eigentlich v1.4.0 im json ausgewählt, trotzdem wird 1.5.0 angezeigt, aber ohne "-ballot", d.h. es sollte funktionieren. Probiert es bitte mal aus. Viel Erfolg.

**Comment by haemka** [comment]
Hi, das ist ja dann aber trotzdem eine andere Version als das 1.4.0, welches von allen anderen 2024er Packages benötigt wird. Und wir können, wie gesagt, keine 2 Versionen des Basisprofils installieren. Das wird also nicht funktionieren.

**Comment by haemka** [comment]
Ihr zieht euch da irgendeine Abhängigkeit neu rein, die vorher gar nicht notwendig war
![image](https://github.com/user-attachments/assets/936badd4-f9a2-4c9d-abf4-4bd9eb14b4ad)

**Comment by Tim-Steinbach-UKB** [comment]
{
  "name": "de.medizininformatikinitiative.kerndatensatz.icu",
  "version": "2024.0.0-alpha1",
  "description": "Medizininformatik Initiative - Modul Intensivmedizin PDMS-Daten und hochauflösende Biosignaldaten",
  "author": "alexanderzautke",
  "fhirVersions": [
    "4.0.1"
  ],
  "dependencies": {
    "de.medizininformatikinitiative.kerndatensatz.prozedur": "2024.0.0-ballot",
    "de.basisprofil.r4": "1.4.0",
    "hl7.fhir.r4.core": "4.0.1",
    "de.medizininformatikinitiative.kerndatensatz.meta": "1.0.3"
  }
}

**Comment by haemka** [comment]
Kann @alexzautke hier vielleicht helfen?

**Comment by Tim-Steinbach-UKB** [comment]
So letzter Versuch sieht besser aus. Probier mal
https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.icu/2024.0.0-alpha4
