### ISSUE TITLE
Display Änderung im ValueSet 'VS_MII_ICU_Category_Procedure_Beatmung_SNOMED'

### ISSUE THREAD

**Issue by christian3Sf6** [medizininformatik-initiative/kerndatensatzmodul-intensivmedizin#23]
Der Displaystring für den SNOMED Code 40617009 hat sich wohl in der SNOMED 2024 Version von _Artificial respiration (procedure)_ zu  _Artificial ventilation (regime/therapy)_ geändert.

**Comment by Tim-Steinbach-UKB** [comment]
Displaywert ist geändert. Danke, den hatten wir übersehen
